#+title: emacs-trans.el

*emacs-trans.el* is a simple wrapper for the excellent [[https://github.com/soimort/translate-shell][translate-shell]] for Emacs. 

** Change log

*0.1.1*
- Added =emacs-trans-url= to open a URL at point (or otherwise provided) in Google Translate via =translate-shell=; minor fixes

*0.1*
- first public release

** Installation

Install translate-shell via your preferred method (=brew install translate-shell=, for example).

Then either clone the repository:

=git clone https://github.com/rtrppl/emacs-trans=

and load the package by adding it to your .emacs or init.el:

#+begin_src elisp
(load "/path/to/emacs-trans/emacs-trans.el") 
#+end_src

or use straight / other package managers:

#+begin_src elisp
(use-package emacs-trans
  :straight (:host github :repo "rtrppl/emacs-trans")
  :bind
  (:map global-map
	("C-c d e n" . emacs-trans-next-sentence)
	("C-c d e i" . emacs-trans-input)
	("C-c d e r" . emacs-trans-region)))
#+end_src

Currently these settings can be modified:

#+begin_src elisp
(setq emacs-trans-show-alternatives "Y") ; will show alternative translation; default is "n"
(setq emacs-trans-show-prompt-message "Y") ; will repeat the prompt; default is "n"
(setq emacs-trans-show-languages "Y") ; will show the identified languages (from the string that this translated); default is "n"
(setq emacs-target-language nil) ; target language; setting this to nil will use the system default language as target > default is ":en"
#+end_src

** Functions

There are four user-facing functions of emacs-trans:

=emacs-trans-next-sentence= and =emacs-trans-region= will translate the next sentence or the active region, respectively. =emacs-trans-input= will translate the input provided. =emacs-trans-url= will open the URL at point with =translate-shell=.

** Integration with elfeed

To send the currently visited post in [[https://github.com/skeeto/elfeed][elfeed]] to Google Translate (via translate-shell/emacs-trans), you have to add this snippet to your init.el:

#+begin_src elisp
(defun elfeed-show-visit-emacs-trans ()
  "Opent the URL of the current Elfeed entry in emacs-trans."
  (interactive)
  (let ((link (elfeed-entry-link elfeed-show-entry)))
    (emacs-trans-url link)))
#+end_src

In order to bind this function to a key, you have to add it to =elfeed-show-mode-map=:

See my elfeed configuration as an example:

#+begin_src elisp
(use-package elfeed
	:defer t
	:bind
	(:map global-map
	      ("C-x w" . elfeed))
	(:map elfeed-search-mode-map
	      ("G" . nil)
	      ("g" . elfeed-search-fetch))
	(:map elfeed-show-mode-map
	      ("w" . elfeed-show-visit-website2org)
	      ("e" . elfeed-show-visit-emacs-trans))
	:config
	(setq-default elfeed-search-filter "@6-months-ago +unread -youtube -later -newspaper"))
#+end_src
